/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ArticlesCatchDeepfakeFraudLayeredIdentityVerificationRouteImport } from './routes/articles.catch-deepfake-fraud-layered-identity-verification'
import { Route as ArticlesPigButcheringScamsIdentityVerificationRouteImport } from './routes/articles.pig-butchering-scams-identity-verification'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesCatchDeepfakeFraudLayeredIdentityVerificationRoute =
  ArticlesCatchDeepfakeFraudLayeredIdentityVerificationRouteImport.update({
    id: '/articles/catch-deepfake-fraud-layered-identity-verification',
    path: '/articles/catch-deepfake-fraud-layered-identity-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesPigButcheringScamsIdentityVerificationRoute =
  ArticlesPigButcheringScamsIdentityVerificationRouteImport.update({
    id: '/articles/pig-butchering-scams-identity-verification',
    path: '/articles/pig-butchering-scams-identity-verification',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work': typeof WorkRoute
  '/articles/catch-deepfake-fraud-layered-identity-verification': typeof ArticlesCatchDeepfakeFraudLayeredIdentityVerificationRoute
  '/articles/pig-butchering-scams-identity-verification': typeof ArticlesPigButcheringScamsIdentityVerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work': typeof WorkRoute
  '/articles/catch-deepfake-fraud-layered-identity-verification': typeof ArticlesCatchDeepfakeFraudLayeredIdentityVerificationRoute
  '/articles/pig-butchering-scams-identity-verification': typeof ArticlesPigButcheringScamsIdentityVerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work': typeof WorkRoute
  '/articles/catch-deepfake-fraud-layered-identity-verification': typeof ArticlesCatchDeepfakeFraudLayeredIdentityVerificationRoute
  '/articles/pig-butchering-scams-identity-verification': typeof ArticlesPigButcheringScamsIdentityVerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/work'
    | '/articles/catch-deepfake-fraud-layered-identity-verification'
    | '/articles/pig-butchering-scams-identity-verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/work'
    | '/articles/catch-deepfake-fraud-layered-identity-verification'
    | '/articles/pig-butchering-scams-identity-verification'
  id:
    | '__root__'
    | '/'
    | '/work'
    | '/articles/catch-deepfake-fraud-layered-identity-verification'
    | '/articles/pig-butchering-scams-identity-verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkRoute: typeof WorkRoute
  ArticlesCatchDeepfakeFraudLayeredIdentityVerificationRoute: typeof ArticlesCatchDeepfakeFraudLayeredIdentityVerificationRoute
  ArticlesPigButcheringScamsIdentityVerificationRoute: typeof ArticlesPigButcheringScamsIdentityVerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/catch-deepfake-fraud-layered-identity-verification': {
      id: '/articles/catch-deepfake-fraud-layered-identity-verification'
      path: '/articles/catch-deepfake-fraud-layered-identity-verification'
      fullPath: '/articles/catch-deepfake-fraud-layered-identity-verification'
      preLoaderRoute: typeof ArticlesCatchDeepfakeFraudLayeredIdentityVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/pig-butchering-scams-identity-verification': {
      id: '/articles/pig-butchering-scams-identity-verification'
      path: '/articles/pig-butchering-scams-identity-verification'
      fullPath: '/articles/pig-butchering-scams-identity-verification'
      preLoaderRoute: typeof ArticlesPigButcheringScamsIdentityVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkRoute: WorkRoute,
  ArticlesCatchDeepfakeFraudLayeredIdentityVerificationRoute:
    ArticlesCatchDeepfakeFraudLayeredIdentityVerificationRoute,
  ArticlesPigButcheringScamsIdentityVerificationRoute:
    ArticlesPigButcheringScamsIdentityVerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
